import Head from 'next/head'
import Navigation from '../components/Navigation'


const changeManager = elem => {
    console.log("Hellooooooo!") 
    console.log(elem)
}


const AboutUs = () => {
    return(
        <>

        <Head>
            <title>CB Academy Blog - Acerca de</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />

            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous"></link>
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>
        </Head>


            <Navigation />

            <h1>All fine !!</h1>

            <input type="text" onChange={(event) => changeManager(event.target.value)} />

            <div className="container">

            </div>



        </>
    )
};


export default AboutUs;

